### ISSUE TITLE
Create Journal Page

### ISSUE THREAD

**Issue by vl4di99** [vl4di99/papafam-hackathon-journal#7]

**Comment by Iqbal955** [comment]
As a developer I want the Journal Page to show me 

- What steps did I take to get closer to my goal (name any, your using this app, so thats something)
- What made me feel like an imposter today?
- Write 3 reasons why that is not true.
- 1 Achievement you did today, in your coding journey

Each item should be writeable and the user must be able to upload this entry.

**Comment by Iqbal955** [comment]
Components:
- index.js 
- Question.js
- QuestionInput.js
- Entry.JS
- Submit.js
